
GET  http://localhost:3003/api/blogs HTTP/1.1

###

POST  http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{  
    "title": "new title",
    "author": "new author",
    "url": "http.com",
    "likes": 5
}

###

DELETE http://localhost:3003/api/blogs/5fe729454b6f821fac1e9321 HTTP/1.1

###

PUT http://localhost:3003/api/blogs/5fdfd2f43d0ec552c0f41d75 HTTP/1.1
content-type: application/json

{
  "title": "SMBC",
  "author": "another dude",
  "url": "smbc...",
  "likes": -1
}

###

GET http://localhost:3003/api/blogs/5fdfd5918f50ca3e04d298f1 HTTP/1.1


// USER CONNECTIONS
### 
GET http://localhost:3003/api/users HTTP/1.1

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
  "username": "user1",
  "name": "tomato",
  "password": "changeme"
}

